<a href="https://colab.research.google.com/github/ashwinihegde22/python/blob/main/22exercise1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


In [3]:
agelist = [10,5,3,9,53]
print(agelist)

[10, 5, 3, 9, 53]


In [4]:
ages = np.array(agelist)
print(type(ages))
print(ages)

<class 'numpy.ndarray'>
[10  5  3  9 53]


In [5]:
print(ages)
print("size:\t",ages.size)
print("shape:\t",ages.shape)

[10  5  3  9 53]
size:	 5
shape:	 (5,)


In [6]:
zeroArr = np.zeros(5)
print(zeroArr)



[0. 0. 0. 0. 0.]


In [7]:
#Multi - dim

weightlist = [65,34,68,54,47]

In [9]:
people = np.array([agelist,weightlist])
print("People:\t" , people)
print("Size:\t" , people.size)
print("Shape:\t", people.shape)

People:	 [[10  5  3  9 53]
 [65 34 68 54 47]]
Size:	 10
Shape:	 (2, 5)


In [11]:
people = people.reshape(10,1)
print("People:\t" , people)
print("Size:\t" , people.size)
print("Shape:\t", people.shape)

People:	 [[10]
 [ 5]
 [ 3]
 [ 9]
 [53]
 [65]
 [34]
 [68]
 [54]
 [47]]
Size:	 10
Shape:	 (10, 1)


In [13]:
import numpy as np
list3 = [7,9,6,33,85,99]
task = np.array([list3])
print("1d array",task)


1d array [[ 7  9  6 33 85 99]]


In [14]:
task = task.reshape(6,1)
print("task",task)

task [[ 7]
 [ 9]
 [ 6]
 [33]
 [85]
 [99]]


In [36]:
a2d = [1,2,4,2,3,0,0,5,1]
a2d = np.array(a2d)
a2d
a2d = a2d.reshape(3,3)
a2d

array([[1, 2, 4],
       [2, 3, 0],
       [0, 5, 1]])

In [26]:
five_timestable = np.arange(0, 55, 5)
five_timestable

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [27]:
fivespaced = np.linspace(0,50,11)
print(fivespaced)

[ 0.  5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


In [28]:
twoAr = np.repeat(2, 10)
print(twoAr)

[2 2 2 2 2 2 2 2 2 2]


In [30]:
identitymatrix = np.eye(5)
print(identitymatrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [31]:
five_timestable

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [32]:
print("1:", 2 * five_timestable)
print("2:", 10 + five_timestable)
print("3:", five_timestable - 1)
print("4:", five_timestable/5)
print("5:", five_timestable **2)
print("6:", five_timestable < 20)

1: [  0  10  20  30  40  50  60  70  80  90 100]
2: [10 15 20 25 30 35 40 45 50 55 60]
3: [-1  4  9 14 19 24 29 34 39 44 49]
4: [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
5: [   0   25  100  225  400  625  900 1225 1600 2025 2500]
6: [ True  True  True  True False False False False False False False]


In [33]:
fiveslist = list(range(0,5001,5))
fiveslist

[0,
 5,
 10,
 15,
 20,
 25,
 30,
 35,
 40,
 45,
 50,
 55,
 60,
 65,
 70,
 75,
 80,
 85,
 90,
 95,
 100,
 105,
 110,
 115,
 120,
 125,
 130,
 135,
 140,
 145,
 150,
 155,
 160,
 165,
 170,
 175,
 180,
 185,
 190,
 195,
 200,
 205,
 210,
 215,
 220,
 225,
 230,
 235,
 240,
 245,
 250,
 255,
 260,
 265,
 270,
 275,
 280,
 285,
 290,
 295,
 300,
 305,
 310,
 315,
 320,
 325,
 330,
 335,
 340,
 345,
 350,
 355,
 360,
 365,
 370,
 375,
 380,
 385,
 390,
 395,
 400,
 405,
 410,
 415,
 420,
 425,
 430,
 435,
 440,
 445,
 450,
 455,
 460,
 465,
 470,
 475,
 480,
 485,
 490,
 495,
 500,
 505,
 510,
 515,
 520,
 525,
 530,
 535,
 540,
 545,
 550,
 555,
 560,
 565,
 570,
 575,
 580,
 585,
 590,
 595,
 600,
 605,
 610,
 615,
 620,
 625,
 630,
 635,
 640,
 645,
 650,
 655,
 660,
 665,
 670,
 675,
 680,
 685,
 690,
 695,
 700,
 705,
 710,
 715,
 720,
 725,
 730,
 735,
 740,
 745,
 750,
 755,
 760,
 765,
 770,
 775,
 780,
 785,
 790,
 795,
 800,
 805,
 810,
 815,
 820,
 825,
 830,
 835,
 840,
 845,
 8

In [34]:
five_times_tablelge = np.arange(0,5001,5)
five_times_tablelge

array([   0,    5,   10, ..., 4990, 4995, 5000])

In [35]:
%timeit five_times_tablelge + 5

1.37 µs ± 11.4 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [38]:
%timeit [e + 5 for e in fiveslist]

59.9 µs ± 973 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [40]:
word = np.array(["ten", "nine", "eight", "seven", "six"])

print(np.isin(word, 'e'))

print("e" in word)
["e" in word1 for word1 in word]

[False False False False False]
False


[True, True, True, True, False]

In [42]:
people.shape = (2, 5)
print(people, "\n")
print(people.T)

[[10  5  3  9 53]
 [65 34 68 54 47]] 

[[10 65]
 [ 5 34]
 [ 3 68]
 [ 9 54]
 [53 47]]


In [43]:
people.dtype

dtype('int64')

In [44]:
ages_with_strings = np.array([10, 5, 8, '32', '65', '43'])
ages_with_strings

array(['10', '5', '8', '32', '65', '43'], dtype='<U21')

In [45]:
ages_with_strings = np.array([10, 5, 8, '32', '65', '43'], dtype='int32')
ages_with_strings

array([10,  5,  8, 32, 65, 43], dtype=int32)

In [46]:
ages_with_strings = np.array([10, 5, 8, '32', '65', '43'])
print(ages_with_strings)


['10' '5' '8' '32' '65' '43']


In [50]:
ages_with_strings.dtype = 'int32'
print(ages_with_strings)

[49 48  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 53  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 56  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 51 50  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0 54 53  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0 52 51  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0]


In [51]:
ages_with_strings.size

126

In [52]:
ages_with_strings.size/21

6.0

In [53]:
np.array([10, 5, 8, '32', '65', '43']).size

6

In [54]:
ages_with_strings = np.array([10, 5, 8, '32', '65', '43'])
print(ages_with_strings)
print(ages_with_strings.astype('int32'))

['10' '5' '8' '32' '65' '43']
[10  5  8 32 65 43]


In [62]:

ex = np. array(['1.4', '2.60', '3.90'])
y = ex. astype(np. float)
print(y) 

[1.4 2.6 3.9]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  


In [65]:


arr = np.array([[15, 2, 30], [48, 35, 96]])

print(f'Original Array:\n{arr}')

arr_transpose = arr.transpose()

print(f'Transposed Array:\n{arr_transpose}')

Original Array:
{arr}
Transposed Array:
{arr_transpose}


In [67]:
myarray = np.array([10, 80, 91, 5, 0, 0])
print(f"My array is: \n{myarray}")

myarray = myarray.astype(dtype=bool)
print(f"My boolean array is: \n{myarray}")

My array is: 
[10 80 91  5  0  0]
My boolean array is: 
[ True  True  True  True False False]


In [68]:
five_timestable

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [70]:
five_timestable[0]

0

In [73]:
five_timestable[-11]

0

In [74]:
five_timestable[:4]

array([ 0,  5, 10, 15])

In [75]:
five_timestable[4:]

array([20, 25, 30, 35, 40, 45, 50])

In [76]:
print(people)
people[:3, :3]

[[10  5  3  9 53]
 [65 34 68 54 47]]


array([[10,  5,  3],
       [65, 34, 68]])

In [77]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [78]:
np.repeat(2,20)

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [81]:
ar_num = np.arange(0,6.28,0.1)
ar_num

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2])

In [100]:
print(ar_num[0:5])




[0.  0.1 0.2 0.3 0.4]


In [102]:


#5.Get the last 3 values
print(ar_num[-3:])


[6.  6.1 6.2]


In [103]:
print(ar_num[3])
print(ar_num[6])

0.30000000000000004
0.6000000000000001


In [84]:
reverse_fivetimestable = np.flip(five_timestable)
reverse_fivetimestable

array([50, 45, 40, 35, 30, 25, 20, 15, 10,  5,  0])

In [85]:
reverse_fivetimestable = five_timestable[-1::-1]
print(reverse_fivetimestable)
five_timestable

[50 45 40 35 30 25 20 15 10  5  0]


array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [86]:
five_timestable[0::3]

array([ 0, 15, 30, 45])

In [105]:
ar = [1,2,3,4,5,66,77,76,87]
ar = np.flip(ar)
ar

array([87, 76, 77, 66,  5,  4,  3,  2,  1])

In [106]:
print(ar[0::4])

[87  5  1]


In [107]:
print(ar[-1::-2])

[ 1  3  5 77 87]


In [87]:
np.array([1.65432, 5.98765]).round(2)

array([1.65, 5.99])

In [89]:
nums = np.arange(0, 4, 0.2555)
nums

array([0.    , 0.2555, 0.511 , 0.7665, 1.022 , 1.2775, 1.533 , 1.7885,
       2.044 , 2.2995, 2.555 , 2.8105, 3.066 , 3.3215, 3.577 , 3.8325])

In [90]:
print("min = ", np.min(nums).round(2))
print("max = ", np.max(nums).round(2))
print("sum = ", np.sum(nums).round(2))
print("mean = ", np.mean(nums).round(2))
print("median = ", np.median(nums).round(2))
print("var = ", np.var(nums).round(2))
print("std = ", np.std(nums).round(2))

min =  0.0
max =  3.83
sum =  30.66
mean =  1.92
median =  1.92
var =  1.39
std =  1.18


In [91]:
flip = np.random.choice([0,1], 10)
flip

array([1, 0, 1, 0, 1, 1, 1, 0, 0, 1])

In [92]:
np.random.rand(10,20,9)

array([[[0.94760158, 0.32735299, 0.07963023, ..., 0.51774387,
         0.07619319, 0.67254648],
        [0.83210335, 0.73652515, 0.15201977, ..., 0.47514646,
         0.89851404, 0.43090644],
        [0.16247287, 0.18988167, 0.8349607 , ..., 0.77575119,
         0.4824986 , 0.47246056],
        ...,
        [0.28086668, 0.85908358, 0.68789773, ..., 0.94239412,
         0.19182923, 0.66348595],
        [0.8115034 , 0.0757843 , 0.51822853, ..., 0.74287646,
         0.96362553, 0.24427922],
        [0.93120734, 0.78435872, 0.90258514, ..., 0.51785849,
         0.78360537, 0.32398285]],

       [[0.58010053, 0.58930572, 0.753574  , ..., 0.57319085,
         0.19160888, 0.08650437],
        [0.00552292, 0.1315393 , 0.49744604, ..., 0.90253998,
         0.38119289, 0.38826034],
        [0.97146032, 0.77610956, 0.08061068, ..., 0.21572593,
         0.29475194, 0.16642912],
        ...,
        [0.60032844, 0.62435067, 0.09228357, ..., 0.72997726,
         0.28682309, 0.52977442],
        [0.0

In [94]:
mu, sigma = 0, 0.1 # mean and standard deviation
s = np.random.normal(mu, sigma, 1000)
s


array([-1.29928766e-01, -9.42512776e-02,  9.66701975e-02, -7.51909837e-02,
       -1.12984697e-01,  7.34987258e-02, -5.81130159e-02,  1.55669825e-01,
        1.68341173e-01, -6.26778971e-02, -1.01704944e-01, -2.04143850e-02,
        4.68908735e-02,  1.76443202e-01,  1.15728953e-01,  5.11835448e-02,
        4.37555819e-02,  1.64795456e-01,  1.53199703e-02,  3.35766701e-02,
       -8.56000895e-02,  1.25942807e-01, -5.91445451e-02,  1.46828123e-01,
        9.82667143e-02, -7.24905969e-02,  6.26397833e-02, -8.98493675e-02,
       -7.62234652e-02,  2.12347410e-01, -1.18026419e-01, -4.84535760e-02,
       -3.77195163e-02, -9.02121772e-03, -5.65933638e-02, -1.58996798e-01,
        5.25959256e-02, -1.81325764e-02, -1.12221090e-01, -1.00358667e-04,
        1.50002663e-01,  1.02094188e-03, -2.04441513e-01,  5.25400094e-03,
       -8.65677880e-02, -1.87147938e-02, -1.68253139e-01, -1.53785887e-01,
        1.77621384e-01,  4.70855072e-02, -1.73508873e-01,  7.77224137e-02,
        1.03875014e-01, -

In [109]:
dice1 = np.random.choice([1,6], 10)
dice1

array([1, 6, 6, 1, 1, 1, 6, 6, 6, 1])

In [114]:
coin1 = np.random.choice(['H','H','T'], 2)
coin1

array(['T', 'H'], dtype='<U1')